/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getDefaultDevice(): string
export function getDevice(): Array<string>
export interface Snapshot {
  total: number
  len: number
}
export class TrafficCenter {
  constructor()
  addListener(interfaceName: string, rule: string): void
  removeListener(rule: string): void
  suspendListener(rule: string): void
  resumeListener(rule: string): void
  getData(rule: string): Snapshot
}
